CREATE INDEX "ticket_comment_parts_comment_idx" ON "ticket_comment_parts" USING btree ("comment_id");--> statement-breakpoint
CREATE INDEX "ticket_comment_parts_part_idx" ON "ticket_comment_parts" USING btree ("part_id");--> statement-breakpoint
CREATE INDEX "contracts_client_idx" ON "contracts" USING btree ("client_id");--> statement-breakpoint
CREATE INDEX "contracts_deal_idx" ON "contracts" USING btree ("deal_id");--> statement-breakpoint
CREATE INDEX "contracts_created_at_idx" ON "contracts" USING btree ("created_at");--> statement-breakpoint
CREATE INDEX "crm_activities_deal_idx" ON "crm_activities" USING btree ("deal_id");--> statement-breakpoint
CREATE INDEX "crm_activities_owner_pending_idx" ON "crm_activities" USING btree ("owner_id","done","due_at");--> statement-breakpoint
CREATE INDEX "crm_activities_pending_due_idx" ON "crm_activities" USING btree ("done","due_at");--> statement-breakpoint
CREATE INDEX "crm_contacts_organization_idx" ON "crm_contacts" USING btree ("organization_id");--> statement-breakpoint
CREATE INDEX "crm_contacts_owner_idx" ON "crm_contacts" USING btree ("owner_id");--> statement-breakpoint
CREATE INDEX "crm_deal_events_deal_idx" ON "crm_deal_events" USING btree ("deal_id","created_at");--> statement-breakpoint
CREATE INDEX "crm_deal_products_deal_idx" ON "crm_deal_products" USING btree ("deal_id");--> statement-breakpoint
CREATE INDEX "crm_deals_stage_status_idx" ON "crm_deals" USING btree ("stage_id","status");--> statement-breakpoint
CREATE INDEX "crm_deals_pipeline_status_idx" ON "crm_deals" USING btree ("pipeline_id","status");--> statement-breakpoint
CREATE INDEX "crm_deals_owner_status_idx" ON "crm_deals" USING btree ("owner_id","status");--> statement-breakpoint
CREATE INDEX "crm_deals_pipeline_closed_idx" ON "crm_deals" USING btree ("pipeline_id","closed_at");--> statement-breakpoint
CREATE INDEX "crm_deals_pipeline_expected_idx" ON "crm_deals" USING btree ("pipeline_id","expected_close_date");--> statement-breakpoint
CREATE INDEX "crm_deals_status_updated_idx" ON "crm_deals" USING btree ("status","updated_at");--> statement-breakpoint
CREATE INDEX "crm_goals_owner_period_idx" ON "crm_goals" USING btree ("owner_id","period_start","period_end");--> statement-breakpoint
CREATE INDEX "crm_notes_deal_idx" ON "crm_notes" USING btree ("deal_id","created_at");--> statement-breakpoint
CREATE INDEX "crm_notes_organization_idx" ON "crm_notes" USING btree ("organization_id");--> statement-breakpoint
CREATE INDEX "crm_organizations_owner_idx" ON "crm_organizations" USING btree ("owner_id");--> statement-breakpoint
CREATE INDEX "crm_organizations_client_idx" ON "crm_organizations" USING btree ("client_id");--> statement-breakpoint
CREATE INDEX "crm_stages_pipeline_order_idx" ON "crm_stages" USING btree ("pipeline_id","order");--> statement-breakpoint
CREATE INDEX "equipment_owner_idx" ON "equipment" USING btree ("owner_id");--> statement-breakpoint
CREATE INDEX "equipment_modules_equipment_idx" ON "equipment_modules" USING btree ("equipment_id");--> statement-breakpoint
CREATE INDEX "equipment_submodules_module_idx" ON "equipment_submodules" USING btree ("module_id");--> statement-breakpoint
CREATE INDEX "leads_status_created_idx" ON "leads" USING btree ("status","created_at");--> statement-breakpoint
CREATE INDEX "ticket_comments_ticket_idx" ON "ticket_comments" USING btree ("ticket_id","created_at");--> statement-breakpoint
CREATE INDEX "tickets_status_priority_idx" ON "tickets" USING btree ("status","priority");--> statement-breakpoint
CREATE INDEX "tickets_assigned_status_idx" ON "tickets" USING btree ("assigned_to_id","status");--> statement-breakpoint
CREATE INDEX "tickets_created_by_idx" ON "tickets" USING btree ("created_by_id","created_at");--> statement-breakpoint
CREATE INDEX "tickets_created_at_idx" ON "tickets" USING btree ("created_at");--> statement-breakpoint
CREATE INDEX "tickets_equipment_idx" ON "tickets" USING btree ("equipment_id");